###
GET http://localhost:8080/redis/find/4
###

###
POST http://localhost:8080/redis/save
Content-Type: application/json

{
  "left": "1111111111",
  "rigth": "2123",
  "top": "2",
  "bottom": "2"
}
###
###
POST http://localhost:8080/redis/update
Content-Type: application/json

{
  "redisid": 4,
  "left": "465464654",
  "rigth": "2123",
  "top": "2",
  "bottom": "2"
}
###

###
GET http://localhost:8080/redis/delete/2
###
