###
GET http://localhost:8080/videoAddress/list?videoaddress=而为人

###

###
POST http://localhost:8080/videoAddress/save
Content-Type: application/json

{
  "videoid": 5,
  "videotag": "昌吉22222",
  "videosource": "比斯33333333",
  "videoaddress": "www.lilil111111111"
}

###

###
GET http://localhost:8080/videoAddress/delete/4

###
